config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :portfolios
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 } # the entry needs to have a title which is between 6 and 100 characters in order to be saved as a database record
  validates :description, presence: true, length: { minimum: 20, maximum: 3500 } # the entry needs to have a description between 20 & 500 words in order to be saved as a database record
  has_one_attached :cover_picture
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 } # the entry needs to have a title which is between 6 and 100 characters in order to be saved as a database record
  validates :description, presence: true, length: { minimum: 20, maximum: 500 } # the entry needs to have a description between 20 & 500 words in order to be saved as a database record
  validates :tech, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    length: { maximum: 105 },
    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in? #this makes the method available to the views and not only to the controller
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :destroy, :update]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  

  def index
    @articles = Article.paginate(page: params[:page])
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params) # require the top level key of 'article' (the database structure) and permit the title and description to be available to create the new article
    @article.user = current_user
    if @article.save # saves the record on the database
      flash[:notice] = "Congrats! Your article has been created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article has been updated."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy    
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id]) # in order to populate the article view for edit, we call the same method which pulls the data from the database
  end
  
  def article_params
    params.require(:article).permit(:title, :description, :cover_picture, :user_id)
    
  end
  

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own articles!"
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only:[:show, :edit, :destroy, :update] # this before_action method is defined at the bottom of the controller under the private section, and is an action performed on the CRUD actions to set the portfolio item prior to executing actions on it.

  def show
  end

  def index
    @portfolios = Portfolio.all
  end

  def new
    @portfolio = Portfolio.new
  end

  def edit
  end

  private

  def set_portfolio   
    @portfolio = Portfolio.find(params[:id]) # in order to populate the article view for edit, we call the same method which pulls the data from the database
  end

  def portfolio_params
    params.require(:portfolio).permit(:title, :description, :tech, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Incorrect login. Please try again."
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile has been updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    
    session[:user_id] = nil if @user == current_user
    
    flash[:notice] = "Account has been deleted... :/"
    redirect_to users_path
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile!"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_center_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto mb-2 d-block")
  end
  def gravatar_right_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mr-auto mb-2 d-block")
  end


  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/articles/_article.html.erb
<div class="card-deck">
  <% @articles.each do |article| %>
    <div class="col-lg-6">
      <div class="card my-4">
      <div class="img-h-sm">
        <%= image_tag(article.cover_picture, alt: "gus dev") %>
      </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article) %></h5>
          <span class="text-muted">Posted by: <%= article.user.username if article.user %></span>
          <p class="card-text"><%= truncate(article.description, :lenght => 50) %></p>
          <% if logged_in? && (article.user == current_user || current_user.admin?)%> 
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-secondary" %>
            <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure you want to delete?" } %>
          <% end %>
          <p class="card-text mt-2">
            <small class="text-muted">Posted <%= time_ago_in_words(article.created_at) %> ago.</small>
            <br/>
            <small class="text-muted">Last updated <%= time_ago_in_words(article.updated_at) %> ago.</small>
          </p>       
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title, class: "text-light" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :description, class: "text-light" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :cover_picture, class: "text-light" %>
    <%= form.file_field :cover_picture, class: "form-control-file btn btn-outline-dark" %>
  </div>
  

  <div class="actions">
    <%= form.submit class: "btn btn-success mb-2" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Edit Article</h1>

  <%= render 'form' %>

  <%= link_to 'Cancel & Return to Articles', articles_path %> 


</div>

app/views/articles/index.html.erb
<div class="container mt-4">
  <h1>Blog Articles</h1>
  <p class="text-light">A collection of articles covering Jekyll, JavaScript, Rails and more.</p>
  <%= render 'article' %>
  <div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>New Article</h1>

  <%= render 'form' %>

  <%= link_to 'Return to Articles', articles_path, class: "btn btn-outline-warning" %> 
</div>

app/views/articles/show.html.erb
<div class="container mt-4">


  <h1 class="my-4">
    <%= @article.title %>
  </h1>
  <div class="img-h-md mb-4 br-1">
    <%= image_tag @article.cover_picture, class: "img-fluid" %>
  </div>
  <div class="mr-auto"><%= link_to gravatar_right_for(@article.user), user_path(@article.user) %></div>
  <span class="text-muted mb-2">Author: <%= @article.user.username if @article.user %></span>
  <p class="text-light mt-2">
    <%= @article.description %>
  </p>
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %> 
    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-primary" %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-outline-danger" %>
  <% end %>
  <%= link_to 'Cancel', articles_path, class: "btn btn-outline-dark" %> 
</div>

app/views/layouts/_footer.html.erb
<body class="d-flex flex-column">
  <div id="page-content">
    <div class="container text-center">
      <div class="row justify-content-center">
        <div class="col-md-7">
        
        </div>
      </div>
    </div>
  </div>
  <footer id="sticky-footer" class="py-4 bg-secondary text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Gus.Dev</small>
    </div>
  </footer>
</body>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <%= link_to "GUS.DEV", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to "Portfolio", portfolios_path, class: "nav-link text-light" %>
        
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Articles</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
          <%= link_to "Create article", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
        </div>
      
        
      </li>
      
      
      <% if logged_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <%= "(Admin)" if current_user.admin? %></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        
          <%= link_to "Your profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
        <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure? All your articles will also be deleted! This cannot be undone!" } %>
          <%= link_to "Log Out", logout_path, class: "dropdown-item", method: :delete %>
        </div>
      
        
      </li>
        <li class="nav-item">
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign-up", signup_path, class: "btn btn-outline-success" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gus.Dev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://fonts.googleapis.com/css2?family=Allerta+Stencil&family=Poppins:wght@100;200;300;400;500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="body">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'Home', root_path %> 
<%= link_to 'Articles', articles_path %> 

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron">
    <h1 >Gus.dev</h1>
    <p class="lead">Let's build cool shit.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign-up!", signup_path, class: "btn btn-primary btn-lg" %>
  </div>
  <main class="mb-4">
    <h3 class="my-4 display-2">From the Blog</h3>
    <div class="card text-center">
      
      <div class="card mb-3">
        <div class="img-h-md">
          <%= image_tag Article.last.cover_picture %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to Article.last.title, Article.last %></h5>
          <p class="card-text"><%= Article.last.description %></p>
          <p class="card-text"><small class="text-muted">Posted <%= time_ago_in_words(Article.last.created_at) %> ago</small></p>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/portfolios/edit.html.erb
<h1>Portfolios#title:string,</h1>
<p>Find me in app/views/portfolios/title:string,.html.erb</p>

app/views/portfolios/index.html.erb
<div class="container my-4">
  <h1>Portfolio</h1>
  <div class="row row-cols-1 row-cols-md-2">
    <% @portfolios.each do |portfolio| %>
      <div class="col-6 mb-4">
        <div class="card">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= link_to portfolio.title, portfolio %></h5>
            <p class="card-text"><%= portfolio.overview %></p>
            <p class="card-text"><small class="text-muted"><%= time_ago_in_words(portfolio.created_at) %></small></p>
            <p class="card-text"><strong>Stack:</strong> <%= portfolio.tech %></p>
          </div>
        </div>
      </div>
    <% end %>  
  </div>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <h5>Portfolio</h5>
  <h1><%= @portfolio.title %>
  <h3><%= @portfolio.overview %></h3>
  <p><%= @portfolio.description %></p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissable fade show" role="alert">
  <ul>
    Please review the following issues:
    <% obj.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
  
<%= form_with(model: @user, local: true) do |form| %>
  <div class="input-group mb-3 w-50 mx-auto">
    <div class="input-group-prepend">
      <%= form.label :username, class: "input-group-text", id: "inputGroup-sizing-default" %>
    </div>
    <%= form.text_field :username, placeholder: "Between 3-25 characters", class: "form-control" %>
  </div>

  <div class="input-group mb-3 w-50 mx-auto">
    <div class="input-group-prepend">
      <%= form.label :email, class: "input-group-text", id: "inputGroup-sizing-default" %>
    </div>
    <%= form.text_field :email, placeholder: "Enter a valid email address", class: "form-control" %>
  </div>
  
  <div class="input-group mb-3 w-50 mx-auto">
    <div class="input-group-prepend">
      <%= form.label :password, class: "input-group-text", id: "inputGroup-sizing-default" %>
    </div>
    <%= form.password_field :password, placeholder: "Enter a strong password", class: "form-control" %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: "btn btn-success align-self-center mr-1" %>
    <%= link_to 'Cancel', root_path, class: "btn btn-dark align-self-center" %> 
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="container">
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-4">
        <div class="card mt-4" style="width: 18rem;">
          <div class="card-body">
            <%= link_to gravatar_center_for(user, size: 150), user %>
            <h5 class="card-title text-center mt-2"><%= link_to user.username, user %></h5>
            <p class="text-center"><small><%= pluralize(user.articles.count, "article") %></small></p>
          </div>
          <ul class="list-group list-group-flush">
            <small class="text-muted text-center mb-4">Latest:</small>
            <% user.articles.take(3).each do |article, id| %>
              <li class="list-group-item text-center"><%= link_to article.title, article %></li>
            <% end %>
          </ul>          
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-4">
  <h1>Edit Profile</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <h1>Our Team</h1>
  <%= render 'user' %>
  <div class="apple_pagination my-4">
    <%= will_paginate @users, :container => false %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container mt-4 bg-light">
  <div class="p-5 text-center">
    <h1 class="text-dark">Sign up, yo!</h1>

    <%= render 'form' %>

    
  </div>

</div>

app/views/users/show.html.erb
<div class="container">
  
  <h1><%= @user.username %>'s Profile</h1>

  <%= gravatar_center_for @user, size: 200 %>
  <% if logged_in? %>
    <% if @user == current_user %> 
      <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-outline-light mt-4" %>
    <% end %>
    <% if current_user.admin? %>
      <%= link_to "Delete Profile", user_path(@user), method: :delete, class: "btn btn-danger mt-4", data: { confirm: "Are you sure? User's articles will be deleted! This cannot be undone!" } %>
    <% end %>
  <% end %>
  

  <h3 class="mt-4">Articles by <%= @user.username %>:</h3>
  <% if logged_in? && @user == current_user %> 
  <%= link_to "Create article", new_article_path, class: "btn btn-outline-primary mt-4" %>
  <% end %>

  <%= render 'articles/article' %>

</div>